safe: true
markdown: kramdown
kramdown:
        input: GFM
highlighter: null
permalink: /:title.html
relative_permalinks: false

default_theme: ribbon
default_width: 792
default_lang: en
default_body_class: list

author:
    name: Julien Tanguy
    url:  http://julien.jhome.fr
    company:
        name: Sounderbox
        url:  http://sounderbox.com

fork_url: https://github.com/shower/shower
progress: true
line_numbers: false
